#!/usr/bin/env python3
"""Open the Lantern local chat app and optional local backend.

This launcher is local-first:
- resolves the checked-in static HTML app;
- writes a read-only repo-state snapshot for the app;
- starts a localhost-only Lantern backend by default;
- opens the app with the operating system default browser;
- does not call GPT, OpenAI, hosted LLMs, tunnels, agents, sensors, or MCP tools.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import sys
from datetime import datetime, timezone
import webbrowser


REPO_ROOT = Path(__file__).resolve().parents[1]
CHAT_DIR = REPO_ROOT / "apps" / "lantern-local-chat"
CHAT_SHELL = CHAT_DIR / "index.html"
RUNTIME_STATE_JS = CHAT_DIR / "runtime-state.js"
LOCAL_BACKEND = CHAT_DIR / "local_lantern_server.py"
DEFAULT_BACKEND_URL = "http://127.0.0.1:8765"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Open the Lantern local chat app.")
    parser.add_argument(
        "--print-only",
        action="store_true",
        help="Print the local file URL without opening a browser or backend.",
    )
    parser.add_argument(
        "--state-only",
        action="store_true",
        help="Write the read-only repo-state snapshot without opening a browser or backend.",
    )
    parser.add_argument(
        "--skip-state",
        action="store_true",
        help="Do not refresh the read-only repo-state snapshot before opening.",
    )
    parser.add_argument(
        "--batch-state",
        action="store_true",
        help="Batch-friendly mode: refresh state, start backend, print evidence, and open the app.",
    )
    parser.add_argument(
        "--no-backend",
        action="store_true",
        help="Do not start the local Lantern backend.",
    )
    parser.add_argument(
        "--backend-url",
        default=DEFAULT_BACKEND_URL,
        help="Backend URL written into runtime-state.js for the browser app.",
    )
    return parser


def _run_git(args: list[str]) -> tuple[int, str, str]:
    """Run one fixed read-only git command in the repository root."""
    result = subprocess.run(
        ["git", *args],
        cwd=REPO_ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    return result.returncode, result.stdout.strip(), result.stderr.strip()


def _read_git_state(backend_url: str) -> dict[str, object]:
    status_code, status_out, status_err = _run_git(["status", "--short"])
    branch_code, branch_out, branch_err = _run_git(["branch", "--show-current"])
    commit_code, commit_out, commit_err = _run_git(["rev-parse", "HEAD"])

    git_available = all(code == 0 for code in (status_code, branch_code, commit_code))
    errors = [err for err in (status_err, branch_err, commit_err) if err]
    git_status_lines = [line for line in status_out.splitlines() if line.strip()]

    return {
        "source": "local batch repo-state snapshot",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "repoPath": str(REPO_ROOT),
        "branch": branch_out if branch_code == 0 else "UNKNOWN",
        "commit": commit_out if commit_code == 0 else "UNKNOWN",
        "gitStatusShort": status_out if status_code == 0 else "UNAVAILABLE",
        "isClean": git_available and len(git_status_lines) == 0,
        "gitAvailable": git_available,
        "errors": errors,
        "groundingMode": "LOCAL_REPO_ANCHOR_BACKEND" if git_available else "UNAVAILABLE_OR_DEGRADED",
        "shellDefault": "cmd.exe",
        "backendUrl": backend_url,
        "boundaries": [
            "read-only git state snapshot",
            "localhost-only Lantern backend",
            "no GPT calls",
            "no hosted LLM endpoint",
            "no command execution from browser",
            "no agents",
            "no tunnels",
            "no sensors",
            "no public writes",
            "no payment or account action",
        ],
    }


def write_runtime_state(backend_url: str = DEFAULT_BACKEND_URL) -> dict[str, object]:
    state = _read_git_state(backend_url)
    CHAT_DIR.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(state, indent=2, sort_keys=True)
    RUNTIME_STATE_JS.write_text(
        "// Generated by scripts/start_lantern_local_chat.py.\n"
        "// Local repo-state snapshot and localhost backend pointer; no GPT call.\n"
        f"window.LANTERN_LOCAL_STATE = {payload};\n",
        encoding="utf-8",
    )
    return state


def start_backend() -> subprocess.Popen[str] | None:
    if not LOCAL_BACKEND.exists():
        print(f"Local Lantern backend not found: {LOCAL_BACKEND}", file=sys.stderr)
        return None
    return subprocess.Popen(
        [sys.executable, str(LOCAL_BACKEND), "--host", "127.0.0.1", "--port", "8765"],
        cwd=REPO_ROOT,
        text=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        creationflags=getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0),
    )


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if not CHAT_SHELL.exists():
        print(f"Lantern local chat app not found: {CHAT_SHELL}", file=sys.stderr)
        return 1

    state: dict[str, object] | None = None
    if not args.skip_state:
        state = write_runtime_state(args.backend_url)

    backend_process = None
    should_start_backend = not args.no_backend and not args.print_only and not args.state_only
    if should_start_backend:
        backend_process = start_backend()

    url = CHAT_SHELL.resolve().as_uri()
    print("Lantern local chat app")
    print(f"URL: {url}")
    print(f"Runtime state: {RUNTIME_STATE_JS}")
    print(f"Backend URL: {args.backend_url}")
    if backend_process is not None:
        print(f"Backend PID: {backend_process.pid}")
    if state is not None:
        print(f"Repo: {state['repoPath']}")
        print(f"Branch: {state['branch']}")
        print(f"Commit: {state['commit']}")
        print(f"Clean: {state['isClean']}")
    print("Boundary: local app plus localhost repo/anchor backend; no GPT/API calls, no agents, no tunnels, no public writes.")

    if args.state_only:
        return 0
    if not args.print_only:
        webbrowser.open(url)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
