#!/usr/bin/env python3
"""Open the Lantern local chat shell without starting servers or agents.

This launcher is intentionally local-first:
- resolves the checked-in static HTML shell;
- writes a read-only repo-state snapshot for the shell;
- opens it with the operating system default browser;
- prints the file URL and boundary text;
- does not call GPT, start Flask, tunnels, agents, sensors, or MCP tools.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import sys
from datetime import datetime, timezone
import webbrowser


REPO_ROOT = Path(__file__).resolve().parents[1]
CHAT_DIR = REPO_ROOT / "apps" / "lantern-local-chat"
CHAT_SHELL = CHAT_DIR / "index.html"
RUNTIME_STATE_JS = CHAT_DIR / "runtime-state.js"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Open the Lantern local chat shell.")
    parser.add_argument(
        "--print-only",
        action="store_true",
        help="Print the local file URL without opening a browser.",
    )
    parser.add_argument(
        "--state-only",
        action="store_true",
        help="Write the read-only repo-state snapshot without opening a browser.",
    )
    parser.add_argument(
        "--skip-state",
        action="store_true",
        help="Do not refresh the read-only repo-state snapshot before opening.",
    )
    parser.add_argument(
        "--batch-state",
        action="store_true",
        help="Batch-friendly mode: refresh state, print evidence, and open the shell.",
    )
    return parser


def _run_git(args: list[str]) -> tuple[int, str, str]:
    """Run one fixed read-only git command in the repository root."""
    result = subprocess.run(
        ["git", *args],
        cwd=REPO_ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    return result.returncode, result.stdout.strip(), result.stderr.strip()


def _read_git_state() -> dict[str, object]:
    status_code, status_out, status_err = _run_git(["status", "--short"])
    branch_code, branch_out, branch_err = _run_git(["branch", "--show-current"])
    commit_code, commit_out, commit_err = _run_git(["rev-parse", "HEAD"])

    git_available = all(code == 0 for code in (status_code, branch_code, commit_code))
    errors = [err for err in (status_err, branch_err, commit_err) if err]
    git_status_lines = [line for line in status_out.splitlines() if line.strip()]

    return {
        "source": "local batch repo-state snapshot",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "repoPath": str(REPO_ROOT),
        "branch": branch_out if branch_code == 0 else "UNKNOWN",
        "commit": commit_out if commit_code == 0 else "UNKNOWN",
        "gitStatusShort": status_out if status_code == 0 else "UNAVAILABLE",
        "isClean": git_available and len(git_status_lines) == 0,
        "gitAvailable": git_available,
        "errors": errors,
        "groundingMode": "FULL_REPO_GROUNDED_FROM_LOCAL_BATCH" if git_available else "UNAVAILABLE_OR_DEGRADED",
        "shellDefault": "cmd.exe",
        "boundaries": [
            "read-only git state snapshot",
            "no GPT calls",
            "no command execution from browser",
            "no agents",
            "no tunnels",
            "no sensors",
            "no public writes",
            "no payment or account action",
        ],
    }


def write_runtime_state() -> dict[str, object]:
    state = _read_git_state()
    CHAT_DIR.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(state, indent=2, sort_keys=True)
    RUNTIME_STATE_JS.write_text(
        "// Generated by scripts/start_lantern_local_chat.py.\n"
        "// Local read-only repo-state snapshot; no GPT call, no network request.\n"
        f"window.LANTERN_LOCAL_STATE = {payload};\n",
        encoding="utf-8",
    )
    return state


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if not CHAT_SHELL.exists():
        print(f"Lantern local chat shell not found: {CHAT_SHELL}", file=sys.stderr)
        return 1

    state: dict[str, object] | None = None
    if not args.skip_state:
        state = write_runtime_state()

    url = CHAT_SHELL.resolve().as_uri()
    print("Lantern local chat shell")
    print(f"URL: {url}")
    print(f"Runtime state: {RUNTIME_STATE_JS}")
    if state is not None:
        print(f"Repo: {state['repoPath']}")
        print(f"Branch: {state['branch']}")
        print(f"Commit: {state['commit']}")
        print(f"Clean: {state['isClean']}")
    print("Boundary: static local page plus read-only repo snapshot; no GPT calls, no command execution, no agents, no tunnels, no public writes.")

    if args.state_only:
        return 0
    if not args.print_only:
        webbrowser.open(url)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
